---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: ECR
      api_url: https://120496071282.dkr.ecr.ap-south-1.amazonaws.com
      prefix: 120496071282.dkr.ecr.ap-south-1.amazonaws.com
      ping: yes

---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: argocd
type: Opaque
data:
  sshPrivateKey:
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBNld0My9qU1Iw
    OUJaaWk4SDIvOWpXU2p0bDh4ZVZ3cFAzZ0FmcHl2NC9mVVF4cGhqCkxqK2JCemtEYlNEL2VRUkNI
    SEkvT0t2VGJrWHkzVzNkWDJoVXozbUNhNlZTRTBORjlRUTZNMHgyZWFueThkL2wKelkxdjA0OVFo
    WjJuaHA0TEJ6cDVNQkRSeml2czBTc0hPNkY5MGY3MHAxbHh1b0NXb1E4VXlLVDdmejJIRjFZdApz
    WFdtNnVTTmRDWUNaejVtY1RSUjhsTHpENVk0a2dXOGltYjNZY0grakZtZFJHYjNHaWIvUThkRzJi
    UzljVHlICmc4UmhaRmFPUFN5M0ZwSUUzRkdNeGFHd3F4eWRtNDZYSlV6by9SZ2JVYWJzMDZ1Z09v
    WUN4MFI4RWNFTkxHTmIKRjNwMGhOcnAxRjk2ODVVeVc0NUFEd1NFRGNIdUlpandkeGtwb1FJREFR
    QUJBb0lCQVFEbDFqZEI3RnVHK0VtaQpZZXJZT2VHR1FtR29yY2hhNWtGOE5CejJ5N3FSdllQMk9N
    aTRHbE01U205UVBrU3YwWHlUYS85S2V3NW1MNlFUCldvRzIxeEZqZFo3eEJja0tSSnlXeE1IV0R6
    MDlVUlZ5Q3VmSmZiSVYyN0VLMEJETDRjUzBLbVIzNnFmYjNhNkMKeTE2RTNkLzVMWldUVHVSSUl5
    T3VsUjMrNzB6Z25FQ0hhK082S3lmRVdETk9ueit0WDhWbXNWNDNFblBkSkc2dgpLTys0S3A3a2Ey
    V0MzR2E5bFpHOUtLMUNpSGtOcHllNktyM3VwTU52WU5pQ0pLb1pjN204Ty9PdFZuTCtvTGQ3Ck9L
    bUs3ZU1IbStGNnZNWkhKSWtaZm4wTWRCaElTd3B2SkNsS3N5NWdBV1RQS052UVBlUnc2RGZBOFZB
    a0lERGUKZVhZWGdIbVJBb0dCQVBXeERvT1ZKOVB3cld3N0txeGpMdXBXUTFyays1dWsrNUZrOFBG
    M3hQelk5aktsdm5vcQpJdHlhQjYvWjlhS0QyeU9sL2NqV05nbkVUdnJOcVFveTBuQW84OHlTakZI
    VzJsek02V0pCdGxFUlhHMEN2Ykt4CkduSjA1MlNsY0wwTjlwRjFiTFVWdTJ5a2cwdEZSWFgydXhM
    Y0wvUm5VYU1XSTJtaUhHelFVKzM5QW9HQkFQTTIKbWhKNTlxQzZjdFB1dkU1R0N4SC83aWdlaHlV
    bHFiVjBpN29aNXk0bFh6Q2FzREFrZU54S0t4VTJIdlJDZldObwpha3FJTlFYbURDdVYxTzJneDly
    L1lIYnhNNXN5S3pZK1BDT25WWjdrbTgwUkN4Z1M3djNSVlFLZlk0ZSthOVJsCjd2SldpM1ZXNGpm
    YVdMOUZEZDN6UG9wVWxvbWZTR1ZwVmdTbE5ZbDFBb0dCQU9LUWt2VE9UL3NHbjdZRjNiVTQKaFdQ
    OWhvRkVWYTNTOTFXOWd0NzVkb05BUTlDeXZUTUV0ajgrSDBhUHRROVhqbmFTTkxUR3JQQld3Z3BR
    S3NqSAowdjB4RnBtWXJxTXRnUkpBdUJzdXc4U0FRUDRabi9zdmpGYnQ3UkFIN0MyNnVaeXJiMEtT
    TnRMWjVtVThEUERhClJPc0FkNHhtMW9hUS9Ma0ZrRGJiNmZtMUFvR0FSdFpRYWJFOE0vUWFIY0Fh
    K0hGT0tCL3lyWnkyb0Fzb01zR1AKTU5UNmtHWXlJMlhxaXhzVVdKVUJsMXY4Q0FpVm5LNTh4dGlG
    R1FLMzZMbnJHb3NKcXE5VzJVM0hTaHlDbVhubQo2anVDcEpUUkRCazZzZmhSdzN1RTF3NjFYb1FI
    eEFVc1kwanh0V3RvMS91d2ZZVVBWT1hVQVZaQndqT3lVbGNyCnhvNlgyVUVDZ1lBaGdmR0cwSVhR
    UlBuQ2xTa2s4bVVURWpCSVdDbUlHaXAzZ3NPbXAzd1l1Lzl2Znp2WVJ6UmYKeWRmNmh4dXl4RVdI
    RzJhdW1sWjgxTmxuMWNPM3NyVU5BbUhQMERuK3lKQlRxeHBaYUFiUzF0RStFWDhRUXVHMApvTUN1
    amRvdm9xQkUzOHJod3IvQm8yV2NySzMrQVdsYmpmL1BubTdINFZVL1JwYzQ5ak1RaVE9PQotLS0t
    LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
