---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd-image-updater-system
data:
  registries.conf: |
    registries:
      - name: ECR
        api_url: https://120496071282.dkr.ecr.ap-south-1.amazonaws.com
        prefix: 120496071282.dkr.ecr.ap-south-1.amazonaws.com
        ping: yes
        credentials: secret:argocd-image-updater-system/ecr-auth-updater
  log.level: debug

---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: argocd
type: Opaque
stringData:
  username: rohitG7496
  password:
